export const NEXT_CAROUSEL_ITEM = "NEXT_CAROUSEL_ITEM";
export const PREVIOUS_CAROUSEL_ITEM = "PREVIOUS_CAROUSEL_ITEM";
export const RESET_ACTIVE_ITEM = "RESET_ACTIVE_ITEM";
export const RESET_PREVIOUS_ITEM = "RESET_PREVIOUS_ITEM";
export const RESET_NEXT_ITEM = "RESET_NEXT_ITEM";
export const STOP_PREVIOUS_ANIMATION = "STOP_PREVIOUS_ANIMATION";
export const STOP_NEXT_ANIMATION = "STOP_NEXT_ANIMATION";
export const TOGGLE_MODEL_VISIBILITY = "TOGGLE_MODEL_VISIBILITY";
